# Настройки сайта
# Доступны через Liquid-теги site.title и т.д.
title: rustycrate.ru
email: rustycrate@michaelpankov.com
description: > # это позволяет отключить переводы строк до начала "baseurl:"
  Неофициальный русскоязычный сайт о языке программирования Rust
# Здесь переводы строк можно делать с помощью <br/>
baseurl: "" # путь до сайта от корня, напр. /blog/. В нашем случае сайт прямо в корне
set: "master"
url: "https://rustycrate.ru" # базовое имя хоста и протокол
# Эти параметры могут использоваться темой для Jekyll, чтобы поставить ссылки на профили
twitter_username:
github_username:  ruRust
paginate: 5
# Настройки по умолчанию для определённых полей front matter
defaults:
  -
    scope:
      path: "" # пустая строка означает "все файлы в проекте"
      type: "posts" # эти настройки влияют на публикации
    values:
      layout: "post" # шаблон по умолчанию
      comments: true # включены ли комментарии
      excerpt_separator: <!--cut-->

# Настройки сборки
# эти файлы и директории будут исключены из обработки Jekyll
exclude: [vendor, Gemfile, Gemfile.lock, travis.trash.id_rsa.enc, node_modules]
markdown: kramdown

kramdown:
  transliterated_header_ids: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

gems:
  - jekyll-assets
  - jekyll-paginate
  - mini_magick
